# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(846, 572)
        self.groupBox = QtWidgets.QGroupBox(dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 831, 151))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_FirmWare_Path_Useing = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FirmWare_Path_Useing.setGeometry(QtCore.QRect(0, 60, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.lineEdit_FirmWare_Path_Useing.setFont(font)
        self.lineEdit_FirmWare_Path_Useing.setAcceptDrops(True)
        self.lineEdit_FirmWare_Path_Useing.setText("")
        self.lineEdit_FirmWare_Path_Useing.setReadOnly(True)
        self.lineEdit_FirmWare_Path_Useing.setObjectName("lineEdit_FirmWare_Path_Useing")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(600, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_FirmWare_Path = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FirmWare_Path.setGeometry(QtCore.QRect(0, 10, 601, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_FirmWare_Path.setFont(font)
        self.lineEdit_FirmWare_Path.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit_FirmWare_Path.setText("")
        self.lineEdit_FirmWare_Path.setObjectName("lineEdit_FirmWare_Path")
        self.lineEdit_FirmWare_Firm_Index = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FirmWare_Firm_Index.setGeometry(QtCore.QRect(480, 60, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.lineEdit_FirmWare_Firm_Index.setFont(font)
        self.lineEdit_FirmWare_Firm_Index.setAcceptDrops(True)
        self.lineEdit_FirmWare_Firm_Index.setText("")
        self.lineEdit_FirmWare_Firm_Index.setReadOnly(True)
        self.lineEdit_FirmWare_Firm_Index.setObjectName("lineEdit_FirmWare_Firm_Index")
        self.pushButton_connect_ap = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_connect_ap.setGeometry(QtCore.QRect(260, 60, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_ap.setFont(font)
        self.pushButton_connect_ap.setObjectName("pushButton_connect_ap")
        self.textBrowser_log = QtWidgets.QTextBrowser(dialog)
        self.textBrowser_log.setGeometry(QtCore.QRect(10, 230, 361, 341))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(14)
        self.textBrowser_log.setFont(font)
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.pushButton_down_firm = QtWidgets.QPushButton(dialog)
        self.pushButton_down_firm.setGeometry(QtCore.QRect(10, 160, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_down_firm.setFont(font)
        self.pushButton_down_firm.setObjectName("pushButton_down_firm")
        self.textBrowser_log_2 = QtWidgets.QTextBrowser(dialog)
        self.textBrowser_log_2.setGeometry(QtCore.QRect(390, 230, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(12)
        self.textBrowser_log_2.setFont(font)
        self.textBrowser_log_2.setPlaceholderText("")
        self.textBrowser_log_2.setObjectName("textBrowser_log_2")
        self.line = QtWidgets.QFrame(dialog)
        self.line.setGeometry(QtCore.QRect(360, 160, 41, 361))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_start_test = QtWidgets.QPushButton(dialog)
        self.pushButton_start_test.setGeometry(QtCore.QRect(390, 160, 451, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_test.setFont(font)
        self.pushButton_start_test.setObjectName("pushButton_start_test")
        self.textBrowser_log_1 = QtWidgets.QTextBrowser(dialog)
        self.textBrowser_log_1.setGeometry(QtCore.QRect(390, 300, 451, 191))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(16)
        self.textBrowser_log_1.setFont(font)
        self.textBrowser_log_1.setPlaceholderText("")
        self.textBrowser_log_1.setObjectName("textBrowser_log_1")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(380, 490, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(380, 530, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(650, 490, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_gprs = QtWidgets.QLineEdit(dialog)
        self.lineEdit_gprs.setGeometry(QtCore.QRect(430, 500, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(16)
        self.lineEdit_gprs.setFont(font)
        self.lineEdit_gprs.setReadOnly(True)
        self.lineEdit_gprs.setObjectName("lineEdit_gprs")
        self.lineEdit_gprs_gprs_rssi = QtWidgets.QLineEdit(dialog)
        self.lineEdit_gprs_gprs_rssi.setGeometry(QtCore.QRect(740, 500, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(16)
        self.lineEdit_gprs_gprs_rssi.setFont(font)
        self.lineEdit_gprs_gprs_rssi.setReadOnly(True)
        self.lineEdit_gprs_gprs_rssi.setObjectName("lineEdit_gprs_gprs_rssi")
        self.lineEdit_gps = QtWidgets.QLineEdit(dialog)
        self.lineEdit_gps.setGeometry(QtCore.QRect(430, 540, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(16)
        self.lineEdit_gps.setFont(font)
        self.lineEdit_gps.setReadOnly(True)
        self.lineEdit_gps.setObjectName("lineEdit_gps")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "033AP固件下载工具"))
        self.groupBox.setTitle(_translate("dialog", "GO GO GO"))
        self.lineEdit_FirmWare_Path_Useing.setToolTip(_translate("dialog", "提示性"))
        self.lineEdit_FirmWare_Path_Useing.setPlaceholderText(_translate("dialog", "Sensor ID"))
        self.pushButton.setText(_translate("dialog", "打开起始固件"))
        self.lineEdit_FirmWare_Path.setPlaceholderText(_translate("dialog", "此处是固件路径"))
        self.lineEdit_FirmWare_Firm_Index.setPlaceholderText(_translate("dialog", "下载个数"))
        self.pushButton_connect_ap.setText(_translate("dialog", "连接AP"))
        self.pushButton_down_firm.setText(_translate("dialog", "下载固件"))
        self.pushButton_start_test.setText(_translate("dialog", "启动测试"))
        self.label.setText(_translate("dialog", "4G:"))
        self.label_2.setText(_translate("dialog", "GPS:"))
        self.label_3.setText(_translate("dialog", "4G_RSSI:"))
        self.lineEdit_gprs.setPlaceholderText(_translate("dialog", "4G Status"))
        self.lineEdit_gprs_gprs_rssi.setPlaceholderText(_translate("dialog", "rssi"))
        self.lineEdit_gps.setPlaceholderText(_translate("dialog", "gps datetime and position"))

